---- Archy session started Tue Jan 15 21:04:34 2013 ----
Traceback (most recent call last):
  File "archy.py", line 27, in <module>
    pygame_run.run_archy()
  File "/Users/developer/DevelopSources/2013/archy-build115/pygame_run.py", line 268, in run_archy
    print debug.get_system_info()
  File "/Users/developer/DevelopSources/2013/archy-build115/debug.py", line 118, in get_system_info
    import version
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 120, in <module>
    _init_module()
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 115, in _init_module
    f = open(BUILD_FILE, "r")
IOError: [Errno 2] No such file or directory: 'build.dat'
---- Archy session started Tue Jan 15 21:04:56 2013 ----
Traceback (most recent call last):
  File "archy.py", line 27, in <module>
    pygame_run.run_archy()
  File "/Users/developer/DevelopSources/2013/archy-build115/pygame_run.py", line 268, in run_archy
    print debug.get_system_info()
  File "/Users/developer/DevelopSources/2013/archy-build115/debug.py", line 118, in get_system_info
    import version
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 120, in <module>
    _init_module()
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 115, in _init_module
    f = open(BUILD_FILE, "r")
IOError: [Errno 2] No such file or directory: 'build.dat'
---- Archy session started Tue Jan 15 21:06:12 2013 ----
Traceback (most recent call last):
  File "archy.py", line 27, in <module>
    pygame_run.run_archy()
  File "/Users/developer/DevelopSources/2013/archy-build115/pygame_run.py", line 268, in run_archy
    print debug.get_system_info()
  File "/Users/developer/DevelopSources/2013/archy-build115/debug.py", line 118, in get_system_info
    import version
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 120, in <module>
    _init_module()
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 115, in _init_module
    f = open(BUILD_FILE, "r")
IOError: [Errno 2] No such file or directory: 'build.dat'
---- Archy session started Tue Jan 15 21:08:06 2013 ----
Traceback (most recent call last):
  File "archy.py", line 27, in <module>
    pygame_run.run_archy()
  File "/Users/developer/DevelopSources/2013/archy-build115/pygame_run.py", line 268, in run_archy
    print debug.get_system_info()
  File "/Users/developer/DevelopSources/2013/archy-build115/debug.py", line 118, in get_system_info
    import version
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 120, in <module>
    _init_module()
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 115, in _init_module
    f = open(BUILD_FILE, "r")
IOError: [Errno 2] No such file or directory: 'build.dat'
---- Archy session started Tue Jan 15 21:09:40 2013 ----
Traceback (most recent call last):
  File "archy.py", line 27, in <module>
    pygame_run.run_archy()
  File "/Users/developer/DevelopSources/2013/archy-build115/pygame_run.py", line 268, in run_archy
    print debug.get_system_info()
  File "/Users/developer/DevelopSources/2013/archy-build115/debug.py", line 118, in get_system_info
    import version
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 120, in <module>
    _init_module()
  File "/Users/developer/DevelopSources/2013/archy-build115/version.py", line 116, in _init_module
    ARCHY_BUILD_NUMBER, ARCHY_BUILD_DATE = f.read().split(",")
ValueError: need more than 1 value to unpack
---- Archy session started Tue Jan 15 21:10:10 2013 ----
System information:
  Archy version: 0.1.1 (build 135 -  12/12/2013)
  Command-line arguments: ['archy.py']
  Platform: darwin
  Python version: 2.7.2 (default, Jun 20 2012, 16:23:33) 
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)]

Warning: one of control keys was not recognized correctly
Spell-check mechanism unavailable.  Disabling spell-checking commands.
init MainTextLayer
DEFAULT ACTION 0
init quasiModeTextLayer
DEFAULT ACTION 0
about to set quasimode to main text entry
There was no Humane Document; using the default text.
Saving text-only backup: _humane_text_0000000000.txt
saved humane document.new
renamed to humane document
received  0  messages
receivemail thread woken up
received  0  messages
receivemail thread woken up
received  0  messages
Saving text-only backup: _humane_text_0000000001.txt
receivemail thread woken up
received  0  messages
receivemail thread woken up
received  0  messages
QuitCommand.execute(): command history size= 99
Saving text-only backup: _humane_text_0000000002.txt
saved humane document.new
renamed to humane document
---- Archy session ended Tue Jan 15 21:12:18 2013 ----
